version: '3.4'

services:
  categorizer:
    build:
      context: ./categorizer
    image: r2r/categorizer
    restart: always

  api:
    build:
      context: ./api
    image: r2r/api
    ports:
      - "5000:80"
    links:
      - categorizer:categorizer
    depends_on:
      - categorizer
    restart: always
